import Header from '@/components/Header'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Providers from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
	weight: ['400', '500', '600'],
	subsets: ['latin'],
})

export const metadata = {
	title: 'Real.est',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<Providers>
					<div className='h-screen bg-background text-secondary-main'>
						<div className='mx-auto flex h-full max-w-[1536px] flex-col'>
							<Header />
							{children}
						</div>
					</div>
				</Providers>
			</body>
		</html>
	)
}
