import React, { ReactNode } from 'react'

export const metadata = {
	title: 'Real.est',
	description: 'Generated by create next app',
}

const Layout = ({ children }: { children: ReactNode }) => {
	return (
		<div className='h-full bg-white p-5 md:w-0 md:flex-grow'>{children}</div>
	)
}

export default Layout
