import React, { ReactNode } from 'react'

export const metadata = {
	title: 'Real.est',
	description: 'Generated by create next app',
}

const Layout = ({ children }: { children: ReactNode }) => {
	return (
		<div className='flex flex-grow flex-col bg-white md:max-h-full md:w-0'>
			<div className='flex flex-col items-center p-5 md:h-0 md:flex-grow md:overflow-auto'>
				{children}
			</div>
		</div>
	)
}

export default Layout

// <div className='flex flex-col bg-white p-5 md:max-h-full md:w-0 md:flex-grow'>
